<?php
require __DIR__ . '/service/database.php';
session_start();
if (empty($_SESSION['is_login'])) { header('Location: halaman_login.php'); exit; }
$userId=(int)$_SESSION['user_id']; $escape=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$memberStmt=$db->prepare('SELECT nama_lengkap,kelas,nis,jurusan FROM user WHERE id=?'); $memberStmt->bind_param('i',$userId); $memberStmt->execute(); $member=$memberStmt->get_result()->fetch_assoc(); $memberStmt->close();
$events=$db->query('SELECT mata_pelajaran,tanggal,jam,ruang,foto_path FROM jadwal_praktikum ORDER BY tanggal ASC,jam ASC');
$announcements=$db->query('SELECT p.judul,p.isi,p.created_at,u.nama_lengkap FROM pengumuman p JOIN user u ON u.id=p.dibuat_oleh ORDER BY p.created_at DESC LIMIT 8');
?><!doctype html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Portal Pelajar | Perkapalan</title><link rel="stylesheet" href="format_css/portal.css"></head><body><main class="portal"><header><div><span>PORTAL PELAJAR</span><h1>Jadwal & Pengumuman</h1><p>Halo, <?php echo $escape($member['nama_lengkap']); ?>. Pantau semua kegiatan praktikmu.</p></div><a href="dashboard.php">Dashboard</a></header><nav><a href="portal_pelajar.php?page=upload">Upload Laporan</a><a class="active" href="portal_utama.php">Jadwal & Info</a><a href="portal_pelajar.php?page=nilai">Nilai Saya</a><a href="portal_pelajar.php?page=profil">Profil</a><a href="chat.php">Chat Grup</a></nav><section class="content"><div class="intro"><h2>Rencana kegiatanmu</h2><p>Jadwal praktik dan kabar terbaru dari guru tersusun di satu tempat.</p></div><div class="info-grid"><section class="info-panel"><h2>Jadwal Praktikum</h2><?php while($row=$events->fetch_assoc()): ?><article class="schedule-card"><b><?php echo $escape($row['mata_pelajaran']); ?></b><span><?php echo $escape($row['tanggal'].' · '.$row['jam'].' · '.$row['ruang']); ?></span><?php if($row['foto_path']): ?><img class="schedule-photo" src="<?php echo $escape($row['foto_path']); ?>" alt="Jadwal <?php echo $escape($row['mata_pelajaran']); ?>"><?php endif; ?></article><?php endwhile; if($events->num_rows===0): ?><p>Belum ada jadwal.</p><?php endif; ?></section><section class="info-panel"><h2>Pengumuman Terbaru</h2><?php while($row=$announcements->fetch_assoc()): ?><article class="announcement-card"><b><?php echo $escape($row['judul']); ?></b><span><?php echo $escape($row['nama_lengkap'].' · '.$row['created_at']); ?></span><p><?php echo nl2br($escape($row['isi'])); ?></p></article><?php endwhile; if($announcements->num_rows===0): ?><p>Belum ada pengumuman.</p><?php endif; ?></section></div></section></main></body></html>
